on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Markdown Linter and fix if possible
        uses: DavidAnson/markdownlint-cli2-action@v1
        with:
          fix: true
          globs: "**/*.md"
